### ISSUE TITLE
What is needed on the Edison?

### ISSUE THREAD

**Issue by mulderp** [zettajs/edison-cli#7]
It is not clear what is necessary to run on the Edison. For example, I was running a `wscat` as follows:

```
root@eddie:~# wscat -l 5888
listening on port 5888 (press CTRL+C to quit)
  client connected
  < {"channel":"command","message":"run"}
> ls
  disconnected

  client connected
  < {"channel":"command","message":"run"}
  disconnected
  client connected
  < {"channel":"command","message":"run"}
  disconnected
  client connected
  < {"channel":"command","message":"run"}
> {"hello": 1}
  disconnected

```

**Comment by AdamMagaluk** [comment]
The `edison-cli` will run on your machine and talk the edison through the network. It uses Intel's xdk daemon that should be running the edison by default. Issue #5 was filed letting me know that intel may not expose the 5888 port to the world anymore, but I have not confirmed this yet with the latest firmware.

In order to send large files through the edison-cli you need to slightly modify one of Intel's Nodejs files on the edison. I have a script that you can run on your machine and point it to a ip or hostname to set it up. Does a few other things as well like enable bluetooth. https://gist.github.com/AdamMagaluk/5e16b010fa3f14033516

Hope that helps.

**Comment by mulderp** [comment]
Thanks! That is great to hear - just wondering how to get the state of the Edison firmware though. I tried:

```
root@eddie:~# uname -a
Linux eddie 3.10.17-poky-edison+ #1 SMP PREEMPT Fri Jan 30 14:16:35 CET 2015 i686 GNU/Linux
```

**Comment by AdamMagaluk** [comment]
Try `configure_edison --version` based on this post https://communities.intel.com/thread/60503

I built this repo off of the firmware they shipped when the edison was first released last year not sure the actual version though.

**Comment by mulderp** [comment]
I get this:

```
configure_edison --version
120
```
